# Generated by Django 5.2.6 on 2025-09-23 04:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_name', models.CharField(max_length=200)),
                ('favorites', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='favorites',
            new_name='sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_name',
        ),
        migrations.AddField(
            model_name='exercise',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='time_spent_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exercises.movement'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='date created')),
                ('time_spent_s', models.IntegerField(default=0)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.user')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.workout')),
            ],
        ),
    ]
