# Generated by Django 5.2.6 on 2025-09-23 14:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_movement_user_rename_favorites_exercise_sets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='date_time',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='time_spent_s',
        ),
        migrations.AddField(
            model_name='exercise',
            name='label',
            field=models.CharField(default='d', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='notes',
            field=models.CharField(default='e', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='exercises.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 14, 1, 40, 750355, tzinfo=datetime.timezone.utc), verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 14, 1, 48, 917300, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='completed',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 14, 1, 56, 898858, tzinfo=datetime.timezone.utc), verbose_name='date completed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='gym',
            field=models.CharField(default='ss', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 14, 2, 22, 601892, tzinfo=datetime.timezone.utc), verbose_name='date started'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.set'),
        ),
        migrations.DeleteModel(
            name='UserWorkout',
        ),
    ]
