# Generated by Django 5.2.6 on 2025-09-24 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_set_rename_date_time_exercise_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='movement_name',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AddField(
            model_name='movement',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='name',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='notes',
            field=models.CharField(blank=True, max_length=32000, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='set_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='label',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.CharField(blank=True, max_length=32000, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='exercises.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='label',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='notes',
            field=models.CharField(blank=True, max_length=32000, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time_spent_s',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='gym',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Workout_Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_idx', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.workout')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='workout_exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercises.workout_exercise'),
            preserve_default=False,
        ),
    ]
