# Generated by Django 4.2.24 on 2025-09-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_user_options_remove_exercise_sets_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='set',
            name='workout_exercise',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='exercises.workout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Workout_Exercise',
        ),
    ]
